from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = f'mirror{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirror{CMD_INDEX}'
        self.CancelMirror = f'cancel{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'list'
        self.SearchCommand = f'search{CMD_INDEX}'
        self.StatusCommand = f'status'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo'
        self.RmSudoCommand = f'rmsudo'
        self.PingCommand = f'ping{CMD_INDEX}'
        self.RestartCommand = f'restart{CMD_INDEX}'
        self.StatsCommand = f'stats{CMD_INDEX}'
        self.HelpCommand = f'help{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.CloneCommand = f'clone{CMD_INDEX}'
        self.CountCommand = f'count{CMD_INDEX}'
        self.WatchCommand = f'watch{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmirror{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirror{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechset22'
        self.SetThumbCommand = f'setthumb22'
        self.LeechCommand = f'leech22'
        self.UnzipLeechCommand = f'unzipleech22'
        self.ZipLeechCommand = f'zipleech22'
        self.QbLeechCommand = f'qbleech22'
        self.QbUnzipLeechCommand = f'qbunzipleech22'
        self.QbZipLeechCommand = f'qbzipleech22'
        self.LeechWatchCommand = f'leechwatch22'
        self.LeechZipWatchCommand = f'leechzipwatch22'
        self.RssListCommand = f'rsslist22'
        self.RssGetCommand = f'rssget22'
        self.RssSubCommand = f'rsssub22'
        self.RssUnSubCommand = f'rssunsub22'
        self.RssSettingsCommand = f'rssset22'
        self.EvalCommand = f'eval{CMD_INDEX}'
        self.ExecCommand = f'exec{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals{CMD_INDEX}'

BotCommands = _BotCommands()
